'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import TeamNav from '../../team-nav';
import './requests.css';
type Entry={id:string;display_name:string;kind:string;start_date:string;end_date:string;details:string;reply_email:string;created_at:string;email_status:string};
export default function Requests({displayName,isManager}:{displayName:string;isManager:boolean}){
 const [entries,setEntries]=useState<Entry[]>([]);const [emailReady,setEmailReady]=useState(false);const [loaded,setLoaded]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [saving,setSaving]=useState(false);const [reference,setReference]=useState('');const [submitted,setSubmitted]=useState(false);
 useEffect(()=>{let active=true;fetch('/api/scheduling-requests').then(async r=>{if(r.status===401){window.location.assign('/login');return;}const data=await r.json();if(!r.ok)throw Error(data.error);if(active){setEntries(data.requests);setEmailReady(data.emailReady);setLoaded(true);}}).catch(()=>{if(active)setError('Requests could not be loaded. Refresh to retry.');});return()=>{active=false;};},[]);
 async function send(payload:Record<string,unknown>){setSaving(true);setError('');setNotice('');try{const r=await fetch('/api/scheduling-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw Error(data.error||'Request was not saved.');setEntries(current=>[data.request,...current.filter(entry=>entry.id!==data.request.id)]);setEmailReady(data.emailReady);setNotice(data.message);setSubmitted(true);}catch(e){setError(e instanceof Error?e.message:'Request was not saved.');}finally{setSaving(false);}}
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const id=reference||crypto.randomUUID();setReference(id);void send({id,kind:form.get('kind'),startDate:form.get('startDate'),endDate:form.get('endDate'),details:form.get('details'),replyEmail:form.get('replyEmail')});}
 return <><TeamNav active="schedule"/><main className="requests-page"><header><div><p className="eyebrow">Hotel Wren</p><h1>Scheduling Request</h1><p>{displayName}</p></div><Link className="button" href="/schedule">Team schedule</Link></header>
 <p>Request time off, a shift change, or an availability update. Requests need Eric’s approval.</p>
 {loaded&&!emailReady&&<p className="request-notice">Requests are saved here for Eric. Email notifications are not connected yet.</p>}
 {error&&<p role="alert">{error}</p>}{notice&&<p className="request-notice" role="status">{notice}</p>}
 {!submitted?<form onSubmit={submit}><fieldset disabled={saving||!loaded}><label>Request type<select name="kind"><option>Time off</option><option>Shift change</option><option>Availability</option><option>Other</option></select></label><div className="request-dates"><label>From<input name="startDate" type="date" required/></label><label>Through<input name="endDate" type="date" required/></label></div><label>Details<textarea name="details" required maxLength={3000} rows={5} placeholder="Include the dates, shifts, or availability you’d like to change."/></label><label>Contact email (optional)<input name="replyEmail" type="email" maxLength={254}/></label><button className="button button-dark" type="submit">{saving?'Saving…':'Submit request'}</button></fieldset></form>:<button className="button" onClick={()=>{setSubmitted(false);setReference('');setNotice('');}}>New request</button>}
 <section className="request-history"><h2>{isManager?'Team requests':'Your requests'}</h2>{!loaded?<p>Loading requests…</p>:!entries.length?<p>No requests yet.</p>:entries.map(entry=><article key={entry.id}><div><h3>{entry.kind}{isManager?' · '+entry.display_name:''}</h3><span>Awaiting review</span></div><p>{entry.start_date} – {entry.end_date}</p><p className="request-details">{entry.details}</p><small>Submitted {new Date(entry.created_at).toLocaleString('en-US',{timeZone:'America/Los_Angeles'})} · {entry.email_status==='sent'?'Email sent':'Email not confirmed'}</small>{entry.email_status!=='sent'&&emailReady&&<button className="text-button" disabled={saving} onClick={()=>void send({id:entry.id})}>Retry email notification</button>}</article>)}</section>
 </main></>;
}
