'use client';
import {useEffect,useState} from 'react';
type State={work_date:string;shift:string;sheet_id:number;sync_error:string|null;updated_at:string};
export default function SheetConnection({date,shift,isManager}:{date:string;shift:string;isManager:boolean}){
 const [state,setState]=useState<{lastSync:string|null;states:State[]}|null>(null),[script,setScript]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false);
 async function load(){try{const r=await fetch('/api/checklist-sync',{cache:'no-store'});if(r.ok){const d=await r.json();if(Array.isArray(d.states))setState(d);}}catch{/* Checklist use remains available if sync status is temporarily unavailable. */}}
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),30000);return()=>clearInterval(timer);},[]);
 async function setup(){setBusy(true);setError('');try{const r=await fetch('/api/checklist-sync',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const d=await r.json();if(!r.ok)throw Error(d.error);setScript(d.script);setCopied(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const current=state?.states.find(s=>s.work_date===date&&s.shift===shift),fresh=state?.lastSync&&Date.now()-Date.parse(state.lastSync)<15*60000;
 return <section className="checklist-sheet-connection"><p>{state?(fresh?'Google Sheets sync is connected. Changes usually appear within five minutes.':state.lastSync?'Google Sheets sync needs attention; your app changes are still saved.':'Google Sheets sync is awaiting authorization. Imported history is available below.'):'Checking Google Sheets connection…'} {current&&<a href={'https://docs.google.com/spreadsheets/d/1kzK1vKnxCYRDqeLX0RbTpoz0Feusqlvwvdf2rBrU51M/edit#gid='+current.sheet_id} target="_blank" rel="noreferrer">Open this shift in Sheets</a>}</p>
 {current?.sync_error&&<div className="checklist-error"><strong>This shift has a sync conflict.</strong><p>{current.sync_error}</p><p>Make the conflicting entry match in the app and sheet, then let sync run again. Eric must reopen a completed shift before changing it.</p></div>}
 {isManager&&<details><summary>Google Sheets connection</summary><p>Checks and task notes sync in both directions. Conflicting edits are flagged instead of overwritten. Completed app shifts stay locked.</p>{state?.lastSync&&<p>Last connection: {new Date(state.lastSync).toLocaleString('en-US',{timeZone:'America/Los_Angeles'})} Pacific.</p>}{!script?<><p>Prepare a private setup script, then authorize it with your Google account. A new setup replaces any previous checklist connection key.</p><button className="button" disabled={busy} onClick={setup}>{busy?'Preparing…':'Prepare Google setup'}</button></>:<><ol><li>Copy the script below.</li><li><a href="https://script.google.com/home/start" target="_blank" rel="noreferrer">Create a private Google Apps Script project</a> and replace its starter code.</li><li>Save, select <strong>installWrenChecklists</strong>, click Run, and authorize access.</li><li>Return here and refresh the connection status.</li></ol><button className="button" onClick={async()=>{try{await navigator.clipboard.writeText(script);setCopied(true);}catch{setError('Select the code and copy it manually.');}}}>{copied?'Copied':'Copy setup script'}</button><textarea aria-label="Private checklist setup script" value={script} readOnly rows={8} onFocus={e=>e.target.select()}/></>}{error&&<p role="alert">{error}</p>}<button className="text-button" onClick={()=>void load()}>Refresh connection status</button></details>}
 </section>;
}
