'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import TeamNav from '../team-nav';
import './projects.css';
const statuses=['To Do','In Progress','Waiting','Done'],priorities=['Low','Normal','High','Urgent'];
type Task={id:string;title:string;notes:string;owner:string;due:string;priority:string;status:string};
type Body={title:string;description:string;owner:string;due:string;priority:string;status:string;tasks:Task[]};
type Project={id:string;body:Body;revision:number;updated_at:string};
type RequestRow={id:string;display_name:string;title:string;details:string;priority:string;due_date:string;status:string;review_note:string;reviewed_by:string;project_id:string|null;created_at:string};
type Comment={id:string;display_name:string;message:string;created_at:string};
type Snapshot={manager:boolean;username:string;projects:Project[];requests:RequestRow[]};
const blank=():Body=>({title:'',description:'',owner:'',due:'',priority:'Normal',status:'To Do',tasks:[]});
const label=(user:string)=>user==='eric'?'Eric Berry':user==='jess'?'Jess':'Unassigned';
const displayDate=(value:string)=>new Date(value+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'});
export default function Projects(){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('projects'),[board,setBoard]=useState(false),[showDone,setShowDone]=useState(false);
 const [selected,setSelected]=useState<Project|null>(null),[draft,setDraft]=useState<Body|null>(null),[dirty,setDirty]=useState(false),[comments,setComments]=useState<Comment[]>([]),[requestOpen,setRequestOpen]=useState(false);
 const requestId=useRef<string|null>(null),commentId=useRef<string|null>(null),createId=useRef<string|null>(null),lock=useRef(false),editor=useRef<HTMLElement|null>(null);
 async function api(body?:unknown,query=''){const r=await fetch('/api/projects'+query,{method:body?'POST':'GET',cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load projects.');return d;}
 async function refresh(){try{setError('');const d=await api();setData(d);if(!d.manager)setTab('requests');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void refresh();},[]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 async function action(work:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await work();}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 function change(next:Body){setDraft(next);setDirty(true);}
 async function open(project:Project){if(dirty&&!window.confirm('Discard your unsaved project changes?'))return;await action(async()=>{const d=await api(undefined,'?project='+project.id);setSelected(d.project);setDraft(structuredClone(d.project.body));setComments(d.comments);setDirty(false);commentId.current=null;setTimeout(()=>editor.current?.scrollIntoView({behavior:'smooth',block:'start'}),0);});}
 function close(){if(dirty&&!window.confirm('Discard your unsaved project changes?'))return;setDraft(null);setSelected(null);setDirty(false);}
 function create(){if(dirty&&!window.confirm('Discard your unsaved project changes?'))return;createId.current=crypto.randomUUID();setSelected(null);setDraft(blank());setComments([]);setDirty(false);setTimeout(()=>editor.current?.scrollIntoView({behavior:'smooth',block:'start'}),0);}
 async function save(e:FormEvent){e.preventDefault();if(!draft)return;await action(async()=>{const d=await api({action:selected?'update':'create',id:selected?.id||createId.current,revision:selected?.revision,body:draft});setSelected(d.project);setDraft(structuredClone(d.project.body));setDirty(false);setNotice('Project saved.');await refresh();});}
 async function submitRequest(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const fields=Object.fromEntries(new FormData(form));requestId.current??=crypto.randomUUID();await action(async()=>{await api({action:'request',id:requestId.current,...fields});requestId.current=null;form.reset();setRequestOpen(false);setNotice('Request submitted for Eric or Jess to review.');await refresh();});}
 async function review(e:FormEvent<HTMLFormElement>,row:RequestRow){e.preventDefault();const form=e.currentTarget;const fields=new FormData(form);const submitter=(e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement;await action(async()=>{await api({action:'review',id:row.id,decision:submitter.value,note:fields.get('note')});setNotice(submitter.value==='Approved'?'Request approved and project created.':'Request declined.');await refresh();});}
 async function comment(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const form=e.currentTarget;const fields=new FormData(form);commentId.current??=crypto.randomUUID();await action(async()=>{await api({action:'comment',id:commentId.current,projectId:selected.id,message:fields.get('message')});commentId.current=null;form.reset();const d=await api(undefined,'?project='+selected.id);setComments(d.comments);});}
 function fields(value:Body|Task,update:(value:any)=>void){return <div className="project-fields"><label>Owner<select value={value.owner} onChange={e=>update({...value,owner:e.target.value})}><option value="">Unassigned</option><option value="eric">Eric Berry</option><option value="jess">Jess</option></select></label><label>Due date<input type="date" value={value.due} onChange={e=>update({...value,due:e.target.value})}/></label><label>Priority<select value={value.priority} onChange={e=>update({...value,priority:e.target.value})}>{priorities.map(p=><option key={p}>{p}</option>)}</select></label><label>Status<select value={value.status} onChange={e=>update({...value,status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label></div>;}
 const visible=data?.projects.filter(p=>showDone||p.body.status!=='Done')||[];
 const mine=data?.projects.flatMap(p=>p.body.status==='Done'?[]:p.body.tasks.filter(t=>t.owner===data.username&&t.status!=='Done').map(t=>({project:p,task:t}))).sort((a,b)=>(a.task.due||'9999').localeCompare(b.task.due||'9999'))||[];
 function card(p:Project){const done=p.body.tasks.filter(t=>t.status==='Done').length;return <button className="project-card" key={p.id} onClick={()=>void open(p)} disabled={busy}><span className="project-status">{p.body.status}</span><strong>{p.body.title}</strong><span>{label(p.body.owner)}{p.body.due?' · '+displayDate(p.body.due):''}</span><div><small>{done} / {p.body.tasks.length} tasks</small><small>{p.body.priority}</small></div><progress value={done} max={p.body.tasks.length||1} aria-label={`${done} of ${p.body.tasks.length} tasks completed`}/></button>;}
 return <><TeamNav active="home"/><main className="projects-page"><header className="projects-heading"><div><p className="eyebrow">THE NEST</p><h1>Projects</h1><p>Good ideas. Thoughtful follow-through.</p></div><div className="project-actions">{data?.manager&&<button className="button button-dark" disabled={busy} onClick={create}>New project</button>}<button className="button" onClick={()=>setRequestOpen(!requestOpen)}>Submit a request</button></div></header>
 {error&&<p className="project-error" role="alert">{error} <button className="text-button" onClick={()=>void refresh()}>Refresh list</button></p>}{notice&&<p className="project-notice" role="status">{notice}</p>}
 {requestOpen&&<form className="project-panel" onSubmit={submitRequest}><h2>Propose a project</h2><p>Eric or Jess will review your request before it becomes a project.</p><fieldset disabled={busy}><label>Project title<input name="title" required maxLength={160} placeholder="What would you like to improve?"/></label><label>Details<textarea name="details" required maxLength={5000} rows={4} placeholder="Describe the idea, why it matters, and what it needs."/></label><div className="project-fields"><label>Priority<select name="priority" defaultValue="Normal">{priorities.map(p=><option key={p}>{p}</option>)}</select></label><label>Preferred due date<input type="date" name="due"/></label></div><button className="button button-dark">{busy?'Submitting…':'Send for approval'}</button></fieldset></form>}
 {!data?<p role="status">Loading projects…</p>:<><nav className="project-tabs" aria-label="Project views">{data.manager&&<button aria-pressed={tab==='projects'} onClick={()=>setTab('projects')}>Projects</button>}<button aria-pressed={tab==='requests'} onClick={()=>setTab('requests')}>{data.manager?'Requests for approval':'Your requests'}{data.manager&&` (${data.requests.filter(r=>r.status==='Pending').length})`}</button></nav>
 {tab==='requests'?<section><h2>{data.manager?'Project requests':'Your project requests'}</h2>{!data.requests.length&&<p className="project-empty">No requests yet. Have an idea? Submit it above.</p>}{data.requests.map(row=><article className="project-request" key={row.id}><div className="project-row"><h3>{row.title}</h3><span className="project-status">{row.status}</span></div><small>{row.display_name} · {row.priority}{row.due_date?' · Requested by '+displayDate(row.due_date):''}</small><p className="project-text">{row.details}</p>{row.review_note&&<p className="project-notice">{label(row.reviewed_by)}: {row.review_note}</p>}{data.manager&&row.status==='Pending'&&<form onSubmit={e=>void review(e,row)}><label>Review note<textarea name="note" maxLength={2000} rows={2}/></label><div className="project-actions"><button name="decision" value="Approved" className="button button-dark" disabled={busy}>Approve & create project</button><button name="decision" value="Declined" className="button" disabled={busy}>Decline</button></div></form>}</article>)}</section>:<>
 {mine.length>0&&<section className="my-project-tasks"><h2>My tasks</h2>{mine.map(({project,task})=><button key={task.id} onClick={()=>void open(project)} disabled={busy}><span><strong>{task.title}</strong><small>{project.body.title}</small></span><span>{task.due?displayDate(task.due):'No due date'}<small>{task.status}</small></span></button>)}</section>}
 <section><div className="project-row"><h2>All projects</h2><div className="project-actions"><label className="project-check"><input type="checkbox" checked={showDone} onChange={e=>setShowDone(e.target.checked)}/>Include completed</label><button className="button project-board-switch" aria-pressed={board} onClick={()=>setBoard(!board)}>{board?'List view':'Board view'}</button></div></div>{!visible.length&&<p className="project-empty">No {showDone?'':'active '}projects yet. Create one or approve a team request.</p>}<div className={board?'project-board':'project-list'}>{board?statuses.map(status=><section key={status}><h3>{status}</h3>{visible.filter(p=>p.body.status===status).map(card)}</section>):visible.map(card)}</div></section></>}
 </>}
 {data?.manager&&draft&&<section className="project-editor project-panel" ref={editor}><div className="project-row"><h2>{selected?'Project details':'New project'}</h2><button className="text-button" onClick={close} disabled={busy}>Close</button></div><form onSubmit={save}><fieldset disabled={busy}><label>Project title<input value={draft.title} onChange={e=>change({...draft,title:e.target.value})} required maxLength={160}/></label><label>Notes<textarea rows={4} value={draft.description} maxLength={5000} onChange={e=>change({...draft,description:e.target.value})}/></label>{fields(draft,change)}<div className="project-row"><h3>Tasks</h3><button type="button" className="button" disabled={draft.tasks.length>=200} onClick={()=>change({...draft,tasks:[...draft.tasks,{id:crypto.randomUUID(),title:'',notes:'',owner:'',due:'',priority:'Normal',status:'To Do'}]})}>Add task</button></div>{draft.tasks.map((task,index)=><div className="project-task" key={task.id}><label>Task {index+1}<input required maxLength={160} value={task.title} onChange={e=>change({...draft,tasks:draft.tasks.map(t=>t.id===task.id?{...t,title:e.target.value}:t)})}/></label>{fields(task,next=>change({...draft,tasks:draft.tasks.map(t=>t.id===task.id?next:t)}))}<label>Task notes<textarea rows={2} maxLength={3000} value={task.notes} onChange={e=>change({...draft,tasks:draft.tasks.map(t=>t.id===task.id?{...t,notes:e.target.value}:t)})}/></label><button type="button" className="text-button" onClick={()=>change({...draft,tasks:draft.tasks.filter(t=>t.id!==task.id)})}>Remove task</button></div>)}<div className="project-actions"><button className="button button-dark">{busy?'Saving…':'Save project'}</button>{selected&&<button type="button" className="button" onClick={()=>void open(selected)}>Reload project</button>}{dirty&&<small>Unsaved changes</small>}</div></fieldset></form>
 {selected&&<section className="project-comments"><h3>Conversation</h3>{comments.map(c=><article key={c.id}><strong>{c.display_name}</strong><small>{new Date(c.created_at).toLocaleString('en-US',{timeZone:'America/Los_Angeles',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})} Pacific</small><p className="project-text">{c.message}</p></article>)}<form onSubmit={comment}><label>Add a comment<textarea name="message" required maxLength={3000} rows={3} disabled={busy}/></label><button className="button" disabled={busy}>Post comment</button></form></section>}
 </section>}
 </main></>;
}
