export const housekeepingSeedItems = [
  {
    "name": "Detergent",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Ultra Fresh · SKU / link label: Laundry Detergent Link · Vendor: Amazon · Price: $74.99 · Source total: $90.15 · Order quantity: 1"
  },
  {
    "name": "OxiClean",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: OxiCLean · SKU / link label: OxiClean Link · Vendor: Costco · Price: $30.67 · Source total: $30.67 · Order quantity: 1"
  },
  {
    "name": "Stain Remover",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Folex · SKU / link label: Stain Remover Link · Vendor: Amazon · Price: $34.95 · Source total: $34.95 · Order quantity: 1"
  },
  {
    "name": "Toilet Bowl Cleaner",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: CloroxPro · SKU / link label: Toilet Bowl Cleaner Link · Vendor: Amazon · Price: $36.55 · Source total: $36.55 · Order quantity: 1"
  },
  {
    "name": "Comet Cleaner",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 2,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Comet · SKU / link label: Comet Cleaner Link · Vendor: Amazon · Price: $73.38 · Source total: $146.76 · Order quantity: 2"
  },
  {
    "name": "Magic Eraser",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 3,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Mr. Clean · SKU / link label: Magic Eraser · Vendor: Amazon · Price: $16.70 · Source total: $50.10 · Order quantity: 3"
  },
  {
    "name": "Spray Bottles",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 3,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Home Depot · SKU / link label: Spray Bottle Link · Vendor: Amazon · Price: $19.95 · Source total: $19.95 · Order quantity: 3"
  },
  {
    "name": "Sprayway Glass Cleaner",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Sprayway · SKU / link label: Sprayway Link · Vendor: Amazon"
  },
  {
    "name": "Glass Cleaner",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Zep · SKU / link label: Glass Cleaner Link · Vendor: Amazon · Price: $22.99 · Source total: $22.99 · Order quantity: 1"
  },
  {
    "name": "Black Trash Liners (23 gal)",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Rubbermaid · SKU / link label: Laundryroom Liner Link · Vendor: Amazon · Price: $37.81 · Source total: $37.81 · Order quantity: 1"
  },
  {
    "name": "Clear Trash Liners (15 gal)",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": ""
  },
  {
    "name": "Room Trash Liners (2 gal)",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Caned · SKU / link label: Room Trash Liner Link · Vendor: Amazon"
  },
  {
    "name": "Dish Soap Refill",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: BioClean · SKU / link label: Dish Soap Refill Link Update · Vendor: Amazon · Price: $69.00 · Source total: $69.00 · Order quantity: 1"
  },
  {
    "name": "Kitchen Sponge",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 20,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Yolaist · SKU / link label: Kitchen Sponge Link · Vendor: Amazon · Price: $9.99 · Source total: $199.80 · Order quantity: 20"
  },
  {
    "name": "Kitchen Towels",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "SKU / link label: N/A"
  },
  {
    "name": "Gloves",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Inspire · SKU / link label: Latex Gloves Linke · Vendor: Amazon"
  },
  {
    "name": "Goo Gone",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Goo Gone · SKU / link label: Goo Gone Link · Vendor: Amazon"
  },
  {
    "name": "CLR",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: CLR · SKU / link label: CLR Link · Vendor: Amazon"
  },
  {
    "name": "Natures Miracle Advanced",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Supplies",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Natures Mirical · SKU / link label: Nature Mirical · Vendor: Amazon"
  },
  {
    "name": "Step Ladder",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 2,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Rubbermaid · SKU / link label: Step Ladder Link · Vendor: Amazon · Price: $54.99 · Source total: $109.98 · Order quantity: 2"
  },
  {
    "name": "Satilo Tile Cleaner",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Zep · SKU / link label: Zep Tile Cleaner · Vendor: Amazon · Price: $12.99 · Source total: $12.98 · Order quantity: 1"
  },
  {
    "name": "Hand Tote",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 3,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Akro-Mils · SKU / link label: Hand Tote · Vendor: Amazon · Price: $15.99 · Source total: $47.97 · Order quantity: 3"
  },
  {
    "name": "Fly Swatter",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Foxany · SKU / link label: Fly Swatter Link · Vendor: Amazon · Price: $6.99 · Source total: $6.99 · Order quantity: 1"
  },
  {
    "name": "Ironing Boards",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Brabantia · SKU / link label: Wire Cutter Iron Board Link · Vendor: Amazon · Price: $145.11 · Source total: $290.22 · Order quantity: 1"
  },
  {
    "name": "Broom",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: KeFanta · SKU / link label: Broom Link Update · Vendor: Amazon · Price: $39.97 · Source total: $39.97 · Order quantity: 1"
  },
  {
    "name": "Push Broom",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Yocada  · SKU / link label: Push Broom Link · Vendor: Amazon · Price: $29.99 · Source total: $29.99 · Order quantity: 1"
  },
  {
    "name": "Mop",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 2,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: OFO · SKU / link label: Mop Link · Vendor: Amazon · Price: $39.98 · Source total: $79.96 · Order quantity: 2"
  },
  {
    "name": "Mop Bucket",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 2,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Amazon Basics · SKU / link label: Mop Bucket Link · Vendor: Amazon · Price: $51.00 · Source total: $102.00 · Order quantity: 2"
  },
  {
    "name": "Toilet Brush",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Rubbermaid · SKU / link label: Jess Toilet Brush · Vendor: Amazon · Price: $33.99 · Source total: $33.99 · Order quantity: 1"
  },
  {
    "name": "Pool Room Trash Bin",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Amazon Basics · SKU / link label: Trash Bin Link · Vendor: Amazon · Price: $64.67 · Source total: $127.82 · Order quantity: 1"
  },
  {
    "name": "Laundry Room Trash Bin",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Amazon Basics · SKU / link label: Trash Bin Link · Vendor: Amazon · Price: $64.67 · Source total: $127.82 · Order quantity: 1"
  },
  {
    "name": "Lint Roller",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Lola Brand · SKU / link label: Lint Roller Link · Vendor: Amazon · Price: $24.00 · Source total: $24.00 · Order quantity: 1"
  },
  {
    "name": "Lint Roller Refill",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 2,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Lola Brand · SKU / link label: Lint Roller Refill · Vendor: Amazon · Price: $44.88 · Source total: $89.76 · Order quantity: 2"
  },
  {
    "name": "Knee Pads",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 2,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: WORKPRO · SKU / link label: Knee Pad Link · Vendor: Amazon · Price: $16.99 · Source total: $33.98 · Order quantity: 2"
  },
  {
    "name": "Rags",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 2,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: SIMPLI-MAGIC · SKU / link label: Terry Rags Link · Vendor: Amazon · Price: $27.82 · Source total: $55.64 · Order quantity: 2"
  },
  {
    "name": "Micro Fiber Rags",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 3,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: The Rag Company · SKU / link label: Micro Fiber Rag Link · Vendor: Amazon · Price: $14.95 · Source total: $44.85 · Order quantity: 3"
  },
  {
    "name": "Bus Tubs",
    "space": "HOUSEKEEPING",
    "zone": "Cleaning Tools",
    "quantity": 0,
    "par": 3,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Rubbermaid · SKU / link label: Bus Tubs Link · Vendor: Amazon · Price: $17.97 · Source total: $53.91 · Order quantity: 3"
  },
  {
    "name": "Portable Steamer",
    "space": "HOUSEKEEPING",
    "zone": "Appliance",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Electrolux · SKU / link label: Steamer Link Update  · Vendor: Amazon · Price: $59.99 · Source total: $119.98 · Order quantity: 1"
  },
  {
    "name": "Vaccum",
    "space": "HOUSEKEEPING",
    "zone": "Appliance",
    "quantity": 0,
    "par": 2,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Oreck · SKU / link label: Vacuum Link · Vendor: Amazon · Price: $165.00 · Source total: $330.00 · Order quantity: 2"
  },
  {
    "name": "Hangers",
    "space": "HOUSEKEEPING",
    "zone": "Rooms",
    "quantity": 0,
    "par": 4,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Topia · SKU / link label: Hanger Link · Vendor: Amazon · Price: $52.99 · Source total: $211.96 · Order quantity: 4"
  },
  {
    "name": "Dental Kit",
    "space": "HOUSEKEEPING",
    "zone": "Toiletries",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Paper Stone · SKU / link label: CODEC024301 · Vendor: La Bottega · Price: $1.35 · Source total: $337.00 · Order quantity: 1"
  },
  {
    "name": "Sewing Repair Kit",
    "space": "HOUSEKEEPING",
    "zone": "Toiletries",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Paper Stone · SKU / link label: CODEC0234 · Vendor: La Bodega · Price: $0.20 · Source total: $100.00 · Order quantity: 1"
  },
  {
    "name": "Shaving Kit",
    "space": "HOUSEKEEPING",
    "zone": "Toiletries",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Paper Stone · SKU / link label: CODEC024201 · Vendor: La Bottega · Price: $1.95 · Source total: $487.50 · Order quantity: 1"
  },
  {
    "name": "Vanity Set",
    "space": "HOUSEKEEPING",
    "zone": "Toiletries",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Paper Stone · SKU / link label: CODEC0232 · Vendor: La Bottega · Price: $0.23 · Source total: $57.50 · Order quantity: 1"
  },
  {
    "name": "Body Wash Pump",
    "space": "HOUSEKEEPING",
    "zone": "Toiletries",
    "quantity": 0,
    "par": 2,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Wonder Valley · SKU / link label: Wonder Valley Order Sheet · Vendor: DAVID PIRROTTA BRANDS · Price: $192.00 · Source total: $384.00 · Order quantity: 2"
  },
  {
    "name": "Shampoo Pump",
    "space": "HOUSEKEEPING",
    "zone": "Toiletries",
    "quantity": 0,
    "par": 2,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Wonder Valley · SKU / link label: Wonder Valley Order Sheet · Vendor: DAVID PIRROTTA BRANDS · Price: $216.00 · Source total: $432.00 · Order quantity: 2"
  },
  {
    "name": "Conditioner Pump",
    "space": "HOUSEKEEPING",
    "zone": "Toiletries",
    "quantity": 0,
    "par": 2,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Wonder Valley · SKU / link label: Wonder Valley Order Sheet · Vendor: DAVID PIRROTTA BRANDS · Price: $228.00 · Source total: $456.00 · Order quantity: 2"
  },
  {
    "name": "Body Wash Refill",
    "space": "HOUSEKEEPING",
    "zone": "Toiletries",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Wonder Valley · SKU / link label: Wonder Valley Order Sheet · Vendor: DAVID PIRROTTA BRANDS"
  },
  {
    "name": "Shampoo Refill",
    "space": "HOUSEKEEPING",
    "zone": "Toiletries",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Wonder Valley · SKU / link label: Wonder Valley Order Sheet · Vendor: DAVID PIRROTTA BRANDS"
  },
  {
    "name": "Conditioner Refill",
    "space": "HOUSEKEEPING",
    "zone": "Toiletries",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Wonder Valley · SKU / link label: Wonder Valley Order Sheet · Vendor: DAVID PIRROTTA BRANDS"
  },
  {
    "name": "Hand Soap",
    "space": "HOUSEKEEPING",
    "zone": "Toiletries",
    "quantity": 0,
    "par": 4,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Salt & Stone · SKU / link label: Hand Soap Link · Vendor: Amazon · Price: $37.96 · Source total: $151.48 · Order quantity: 4"
  },
  {
    "name": "Toilet Paper (Need Septic)",
    "space": "HOUSEKEEPING",
    "zone": "Toiletries",
    "quantity": 0,
    "par": 2,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Scott Brand · SKU / link label: Toilet Paper Link · Vendor: Amazon · Price: $56.38 · Source total: $112.76 · Order quantity: 2"
  },
  {
    "name": "Facial Tissue Paper",
    "space": "HOUSEKEEPING",
    "zone": "Toiletries",
    "quantity": 0,
    "par": 3,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Kleenex  · SKU / link label: Facial Tissue Link · Vendor: Amazon · Price: $87.99 · Source total: $263.97 · Order quantity: 3"
  },
  {
    "name": "Paper Towels",
    "space": "HOUSEKEEPING",
    "zone": "Toiletries",
    "quantity": 0,
    "par": 4,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Amazon Commercial · SKU / link label: Paper Towel Link · Vendor: Amazon · Price: $56.05 · Source total: $224.20 · Order quantity: 4"
  },
  {
    "name": "Housekeeping Uniforms",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 6,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Dagacci · SKU / link label: Housekeeping Uniform Link · Vendor: Amazon · Price: $23.99 · Source total: $23.99 · Order quantity: 6"
  },
  {
    "name": "Pool Towels",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Kassatex · SKU / link label: Ibiza Pool Towel White/Linen"
  },
  {
    "name": "Make Up Towel",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 3,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: H-TWLMKPBLKONE · Vendor: Parachute · Price: $5.04 · Source total: $181.44 · Order quantity: 3"
  },
  {
    "name": "Pillow Covers (Standard)",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · Vendor: Parachute"
  },
  {
    "name": "Robes",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 4,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: HSP-BRBGAZWHTLRG · Vendor: Parachute · Price: $199.29 · Source total: $7,174.44 · Order quantity: 4"
  },
  {
    "name": "Wash Cloths",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: TWLHSPWHTWSH · Vendor: Parachute · Price: -$5.52 · Source total: -$615.46 · Order quantity: -0.3"
  },
  {
    "name": "Pillow Protectors (King)",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · Vendor: Parachute"
  },
  {
    "name": "King Sheet (Flat)",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 3,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: PRM-FLTPERWHTKNG · Vendor: Parachute · Price: $26.53 · Source total: $955.08 · Order quantity: 3"
  },
  {
    "name": "King Duvet Cover",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 3,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: PRM-DUVPERWHTKNG · Vendor: Parachute · Price: $40.90 · Source total: $1,472.40 · Order quantity: 3"
  },
  {
    "name": "Queen Duvet Cover",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: PRM-DUVPERWHTQUE · Vendor: Parachute"
  },
  {
    "name": "Queen Sheet (Flat)",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: PRM-FLTPERWHTQUE · Vendor: Parachute · Price: $25.45 · Source total: $305.40 · Order quantity: 1"
  },
  {
    "name": "Cal King Sheet (Fitted)",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 3,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: PRM-FTTPERWHTCAK H · Vendor: Parachute · Price: $23.63 · Source total: $850.68 · Order quantity: 3"
  },
  {
    "name": "Queen Sheet (Fitted)",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: PRM-FTTPERWHTQUE · Vendor: Parachute · Price: $19.99 · Source total: $239.88 · Order quantity: 1"
  },
  {
    "name": "Pillow Cases (King)",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: PRM-PFLPERWHTKNG · Vendor: Parachute"
  },
  {
    "name": "Pillow Cases (Standard )",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: PRM-PFLPERWHTSTD · Vendor: Parachute · Price: $3.63 · Source total: $174.24 · Order quantity: 1"
  },
  {
    "name": "Bath Towels",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: TWLHSPWHTBTH · Vendor: Parachute · Price: -$0.68 · Source total: -$196.13 · Order quantity: 0.7"
  },
  {
    "name": "Hand Towels",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: TWLHSPWHTHND · Vendor: Parachute · Price: -$3.10 · Source total: -$405.79 · Order quantity: 0.2"
  },
  {
    "name": "Wash Cloths",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: TWLHSPWHTWSH · Vendor: Parachute · Price: $2.76 · Source total: $264.96 · Order quantity: 1"
  },
  {
    "name": "Bath Mat",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: TWLHSPWHTMAT · Vendor: Parachute · Price: $8.67 · Source total: $312.12 · Order quantity: 1"
  },
  {
    "name": "Duvet Insert All Season (King)",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 3,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: HSP-ASNCFRADNKCK · Vendor: Parachute · Price: $142.88 · Source total: $2,571.84 · Order quantity: 3"
  },
  {
    "name": "Duvet Insert All Season (Queen)",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 3,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: LWTCFRADNFQN · Vendor: Parachute · Price: $142.88 · Source total: $2,571.84 · Order quantity: 3"
  },
  {
    "name": "Pillow Insert Medium (King)",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 3,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: HSP-PLWADNMEDKNG · Vendor: Parachute · Price: $27.24 · Source total: $817.20 · Order quantity: 3"
  },
  {
    "name": "Pillow Insert Medium (Standard)",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: HSP-PLWADNMEDSTD · Vendor: Parachute · Price: $21.97 · Source total: $307.58 · Order quantity: 1"
  },
  {
    "name": "Pillow Insert Firm (King)",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 4,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: HSP-PLWADNFRMKNG · Vendor: Parachute · Price: $31.97 · Source total: $1,023.04 · Order quantity: 4"
  },
  {
    "name": "Pillow Insert Firm (Standard)",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 1,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: HSP-PLWADNFRMSTD · Vendor: Parachute · Price: $23.79 · Source total: $335.58 · Order quantity: 1"
  },
  {
    "name": "Robes",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 2,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Parachute · SKU / link label: HSP-BRBGAZWHTLRG · Vendor: Parachute · Price: $72.21 · Source total: $2,599.56 · Order quantity: 2"
  },
  {
    "name": "Tan Wash Cloths",
    "space": "HOUSEKEEPING",
    "zone": "Soft Goods/Linen",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": ""
  },
  {
    "name": "Bowls",
    "space": "HOUSEKEEPING",
    "zone": "Dog Supplies",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Yeti · SKU / link label: Dog Bowl Link · Vendor: Amazon"
  },
  {
    "name": "Big Mats",
    "space": "HOUSEKEEPING",
    "zone": "Dog Supplies",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Dogbuddy · SKU / link label: Dog Mat Link · Vendor: Amazon"
  },
  {
    "name": "Small Mats",
    "space": "HOUSEKEEPING",
    "zone": "Dog Supplies",
    "quantity": 0,
    "par": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Dogbuddy · SKU / link label: Dog Mat Link · Vendor: Amazon"
  }
] as const;
