export const minibarProducts = [
  {
    "name": "Mal Bien Mezcal Espadin",
    "brand": "Mal Bien",
    "size": "200 ml",
    "zone": "Mini Bar — Basket",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Mal Bien. Size: 200 ml. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Madre Blanco Tequila",
    "brand": "Madre",
    "size": "200 ml",
    "zone": "Mini Bar — Basket",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Madre. Size: 200 ml. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Woodford Reserve Kentucky Straight Bourbon Whiskey",
    "brand": "Woodford Reserve",
    "size": "200 ml",
    "zone": "Mini Bar — Basket",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Woodford Reserve. Size: 200 ml. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "St. George Spirits Vodka",
    "brand": "St. George",
    "size": "200 ml",
    "zone": "Mini Bar — Basket",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: St. George. Size: 200 ml. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Wilderness First Aid Kit",
    "brand": "Kikkerland Design Inc",
    "size": "",
    "zone": "Mini Bar — Basket",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Kikkerland Design Inc. Size needs confirmation. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Complete Calm Sleep Gummies (Melatonin-Free)",
    "brand": "Asystem",
    "size": "",
    "zone": "Mini Bar — Basket",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Asystem. Size needs confirmation. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Have’a Corn Chips",
    "brand": "Have’A Chips",
    "size": "4 oz",
    "zone": "Mini Bar — Basket",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Have’A Chips. Size: 4 oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Salt & Vinegar Chips",
    "brand": "Sal de Ibiza",
    "size": "",
    "zone": "Mini Bar — Basket",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Sal de Ibiza. Size needs confirmation. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed. Salt-and-vinegar replacement; Sal de Ibiza matched to the existing Windsong catalog, confirm brand."
  },
  {
    "name": "Classic BjornQorn",
    "brand": "BjornQorn",
    "size": "3 oz",
    "zone": "Mini Bar — Basket",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: BjornQorn. Size: 3 oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Pistachio Crunchy Nut Bar",
    "brand": "South Forty Snacks Company",
    "size": "1.4 oz",
    "zone": "Mini Bar — Basket",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: South Forty Snacks Company. Size: 1.4 oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Señor Mango Enchilado",
    "brand": "Señor Mango",
    "size": "60 g",
    "zone": "Mini Bar — Basket",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Señor Mango. Size: 60 g. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Sweet & Salty Pecans",
    "brand": "Evie’s Snacks",
    "size": "3 oz",
    "zone": "Mini Bar — Basket",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Evie’s Snacks. Size: 3 oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Chocolate Chip Cookies",
    "brand": "Tate’s",
    "size": "3.5 oz",
    "zone": "Mini Bar — Basket",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Tate’s. Size: 3.5 oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Coco Rolls Original Rolled Coconut Wafer",
    "brand": "Sun Tropics",
    "size": "4 oz",
    "zone": "Mini Bar — Basket",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Sun Tropics. Size: 4 oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Sour Wild Strawberry Fish — Swedish Candy",
    "brand": "BonBon",
    "size": "5.2 oz",
    "zone": "Mini Bar — Basket",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: BonBon. Size: 5.2 oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Pretzel Case",
    "brand": "Hey Champ",
    "size": "1 oz",
    "zone": "Mini Bar — Basket",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Hey Champ. Size: 1 oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Dark Chocolate Almonds and Sea Salt Bar",
    "brand": "Chocolove",
    "size": "3.2 oz",
    "zone": "Mini Bar — Basket",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Chocolove. Size: 3.2 oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Sencha Shot Japanese Green Tea",
    "brand": "Ito En",
    "size": "6.4 fl oz",
    "zone": "Mini Bar — Fridge",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Ito En. Size: 6.4 fl oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Canyon Cold Brew — Classic",
    "brand": "Canyon Coffee",
    "size": "8 fl oz",
    "zone": "Mini Bar — Fridge",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Canyon Coffee. Size: 8 fl oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Le Spritz",
    "brand": "Ghia",
    "size": "",
    "zone": "Mini Bar — Fridge",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Ghia. Size needs confirmation. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Maracuyá — Sparkling Passion Fruit",
    "brand": "Frescos Naturales",
    "size": "12 fl oz",
    "zone": "Mini Bar — Fridge",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Frescos Naturales. Size: 12 fl oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Apple Juice",
    "brand": "Lovely Bunch",
    "size": "10.4 oz",
    "zone": "Mini Bar — Fridge",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Lovely Bunch. Size: 10.4 oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Visitor Original Lager",
    "brand": "Visitor",
    "size": "",
    "zone": "Mini Bar — Fridge",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Visitor. Size needs confirmation. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Sparkling Water",
    "brand": "Topo Chico",
    "size": "12 oz",
    "zone": "Mini Bar — Fridge",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Topo Chico. Size: 12 oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Cascade Mountain Water",
    "brand": "Cascade",
    "size": "",
    "zone": "Mini Bar — Fridge",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Cascade. Size needs confirmation. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Scribe Nouveau of Pinot Noir",
    "brand": "Scribe",
    "size": "750 ml",
    "zone": "Mini Bar — Fridge",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Scribe. Size: 750 ml. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Wavy Wines LS Gris",
    "brand": "Wavy Wines",
    "size": "750 ml",
    "zone": "Mini Bar — Fridge",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Wavy Wines. Size: 750 ml. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Domaine Le Facteur Extra Brut Vouvray Sparkling NV",
    "brand": "Domaine Le Facteur",
    "size": "750 ml",
    "zone": "Mini Bar — Fridge",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Domaine Le Facteur. Size: 750 ml. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Bizzarro Yuzu Spritz",
    "brand": "Delinquente",
    "size": "250 ml",
    "zone": "Mini Bar — Fridge",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Delinquente. Size: 250 ml. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Desert Water — Grapefruit",
    "brand": "Madre",
    "size": "12 oz",
    "zone": "Mini Bar — Fridge",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Madre. Size: 12 oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Desert Water — Prickly Pear",
    "brand": "Madre",
    "size": "12 oz",
    "zone": "Mini Bar — Fridge",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Madre. Size: 12 oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Jean Pierre Robinot VDF Sparkling NV Can",
    "brand": "Famille du Vin",
    "size": "200 ml",
    "zone": "Mini Bar — Fridge",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Famille du Vin. Size: 200 ml. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Taillelandier Orange NV Can",
    "brand": "Famille du Vin",
    "size": "200 ml",
    "zone": "Mini Bar — Fridge",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Famille du Vin. Size: 200 ml. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Jean Baptiste et Charlotte Sénat VDF Red France",
    "brand": "Famille du Vin",
    "size": "200 ml",
    "zone": "Mini Bar — Fridge",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Famille du Vin. Size: 200 ml. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Ysidro Spritz",
    "brand": "Ysidro",
    "size": "250 ml",
    "zone": "Mini Bar — Fridge",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Ysidro. Size: 250 ml. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "pFriem Pilsner",
    "brand": "pFriem",
    "size": "",
    "zone": "Mini Bar — Fridge",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: pFriem. Size needs confirmation. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Anderson Valley Blood Orange Gose",
    "brand": "Anderson Valley",
    "size": "12 oz",
    "zone": "Mini Bar — Fridge",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Anderson Valley. Size: 12 oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Fort Point Animal IPA",
    "brand": "Fort Point",
    "size": "12 oz",
    "zone": "Mini Bar — Fridge",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Fort Point. Size: 12 oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Offshoot Relax Hazy",
    "brand": "Offshoot",
    "size": "16 oz",
    "zone": "Mini Bar — Fridge",
    "par": 2,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Offshoot. Size: 16 oz. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  },
  {
    "name": "Acqua Panna",
    "brand": "Acqua Panna",
    "size": "",
    "zone": "Mini Bar — Fridge",
    "par": 1,
    "quantity": 0,
    "unit": "each",
    "status": "Count needed",
    "photo": "",
    "reorderUrl": "",
    "notes": "Brand: Acqua Panna. Size needs confirmation. Room stocking target from the minibar checklist and approved handwritten revisions (2026-09-20). Physical count not yet confirmed."
  }
];

export const checklistMinibarSeedItems = Array.from({ length: 12 }, (_, index) =>
  minibarProducts.map(({ brand: _brand, size: _size, ...item }) => ({ ...item, space: `ROOM ${String(index + 1).padStart(2, "0")}` }))
).flat();
