'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import TeamNav from '../../team-nav';
import './ask-wren.css';
type Recognition={lang:string;interimResults:boolean;continuous:boolean;onresult:((event:{results:{[key:number]:{[key:number]:{transcript:string}}}})=>void)|null;onerror:((event:{error:string})=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void;abort:()=>void};
type VoiceWindow=Window&{SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};
type Source={id:number;name:string;space:string;zone:string;quantity:number|null;unit:string;vendor:string|null;reorderUrl:string|null;updatedAt:string|null};
export default function AskWren(){
 const [question,setQuestion]=useState('');const [answer,setAnswer]=useState('');const [sources,setSources]=useState<Source[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [listening,setListening]=useState(false);const [voice,setVoice]=useState(false);const [canSpeak,setCanSpeak]=useState(false);const [speaking,setSpeaking]=useState(false);const recognition=useRef<Recognition|null>(null);
 useEffect(()=>{const w=window as VoiceWindow;setVoice(!!(w.SpeechRecognition||w.webkitSpeechRecognition));setCanSpeak('speechSynthesis' in window);return()=>{if(recognition.current){recognition.current.onresult=null;recognition.current.onerror=null;recognition.current.onend=null;recognition.current.abort();}window.speechSynthesis?.cancel();};},[]);
 function dictate(){if(listening){recognition.current?.stop();return;}const w=window as VoiceWindow;const Constructor=w.SpeechRecognition||w.webkitSpeechRecognition;if(!Constructor)return;window.speechSynthesis?.cancel();setSpeaking(false);setError('');const r=new Constructor();recognition.current=r;r.lang='en-US';r.interimResults=false;r.continuous=false;r.onresult=event=>setQuestion(event.results[0][0].transcript.slice(0,500));r.onerror=event=>{setListening(false);setError(event.error==='not-allowed'?'Microphone access was declined. You can type your question instead.':'Voice input stopped. Try again or type your question.');};r.onend=()=>setListening(false);try{r.start();setListening(true);}catch{setError('Voice input is unavailable. Type your question instead.');}}
 async function ask(event:FormEvent){event.preventDefault();recognition.current?.stop();window.speechSynthesis?.cancel();setSpeaking(false);setBusy(true);setError('');setAnswer('');setSources([]);try{const r=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});const data=await r.json();if(!r.ok)throw Error(data.error||'Please try again.');setAnswer(data.answer);setSources(data.sources);}catch(e){setError(e instanceof Error?e.message:'Unable to answer.');}finally{setBusy(false);}}
 function readAnswer(){if(speaking){window.speechSynthesis.cancel();setSpeaking(false);return;}const speech=new SpeechSynthesisUtterance(answer);speech.lang='en-US';speech.onend=()=>setSpeaking(false);speech.onerror=()=>setSpeaking(false);window.speechSynthesis.speak(speech);setSpeaking(true);}
 return <><TeamNav active="inventory"/><main className="ask-wren"><header><div><p className="eyebrow">Hotel Wren</p><h1>Ask Maria</h1></div><Link className="button" href="/inventory">Inventory</Link></header><p>Ask about stock, where an item lives, or its recorded supplier.</p><form onSubmit={ask}><label htmlFor="wren-question">Your question</label><textarea id="wren-question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={500} rows={3} required placeholder="Where do we get Canyon Coffee?" disabled={busy}/><div>{voice&&<button className="button voice-button" type="button" disabled={busy} aria-pressed={listening} onClick={dictate}><svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10v1a7 7 0 0 0 14 0v-1M12 18v4m-4 0h8"/></svg>{listening?'Stop listening':'Use microphone'}</button>}<button className="button button-dark" disabled={busy||listening||!question.trim()}>{busy?'Looking it up…':'Ask Maria'}</button></div><small>{voice?'Tap the microphone to dictate, review the text, then ask. Your browser may use its speech service.':'Voice input isn’t supported in this browser. You can type your question.'}</small></form>{listening&&<p role="status">Listening…</p>}{error&&<p role="alert">{error}</p>}{answer&&<section className="wren-answer" aria-live="polite"><h2>Answer</h2><p>{answer}</p>{canSpeak&&<button className="text-button" onClick={readAnswer}>{speaking?'Stop reading':'Read answer aloud'}</button>}{sources.length>0&&<details><summary>Inventory records used ({sources.length})</summary>{sources.map(source=><article key={source.id}><strong>{source.name}</strong><span>{source.space} · {source.zone}</span><span>{source.quantity===null?'Count needed':`${source.quantity} ${source.unit} recorded`}</span>{source.vendor&&<span>Supplier: {source.vendor}</span>}{source.reorderUrl&&/^https?:\/\//i.test(source.reorderUrl)&&<a href={source.reorderUrl} target="_blank" rel="noreferrer">Reorder source</a>}</article>)}</details>}<small>Based on saved inventory records. Confirm physical stock before ordering.</small></section>}</main></>;
}
