"use client";
import { useEffect, useState } from "react";
type Item = {id:number;name:string;space:string;quantity:number;par:number;unit:string;unitCost?:number|null;status:string};
type Quote = {id:string;itemId:number;vendor:string;pack:number;price:number;shipping:number;minimum:number;days:number};
type Purchase = {id:string;item:string;vendor:string;quantity:number;total:number;status:string;date:string};
type Snapshot = {month:string;date:string;items:Item[]};
type State = {quotes:Quote[];purchases:Purchase[];snapshots:Snapshot[]};
const empty:State={quotes:[],purchases:[],snapshots:[]};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
export function purchaseApproval(total:number) {
 const cents=Math.round(total*100);
 return cents>50000?'Draft — Eric and Jess approval required':cents>7500?'Draft — Eric approval required':'Draft — no approval required';
}
export function orderCost(q:Quote,shortage:number) {const packs=Math.max(q.minimum,Math.ceil(shortage/q.pack));return {packs,units:packs*q.pack,total:packs*q.price+q.shipping};}
const monthKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;
export default function StockControls({items,onItem}:{items:Item[];onItem:(id:number)=>void}) {
 const [data,setData]=useState<State>(empty),[ready,setReady]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState(''),[month,setMonth]=useState(monthKey(new Date()));
 // Hydrate browser-only records after the server render.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{try{const saved=localStorage.getItem('nest-stock-controls-v1');if(saved)setData(JSON.parse(saved));setReady(true);}catch{setError('Saved purchasing records could not be loaded. They have not been overwritten.');}},[]);
 function save(next:State){try{localStorage.setItem('nest-stock-controls-v1',JSON.stringify(next));setData(next);setError('');}catch{setError('Could not save. Free browser storage and try again.');}}
 const low=items.filter(i=>i.par>0&&i.quantity<i.par);
 const chosen=items.find(i=>i.id===Number(selected));
 const quotes=data.quotes.filter(q=>q.itemId===chosen?.id).sort((a,b)=>orderCost(a,Math.max(1,(chosen?.par||0)-(chosen?.quantity||0))).total-orderCost(b,Math.max(1,(chosen?.par||0)-(chosen?.quantity||0))).total);
 const snapshots=[...data.snapshots].sort((a,b)=>b.month.localeCompare(a.month));
 const latest=snapshots[0]; const previousMonth=latest?(()=>{const [y,m]=latest.month.split('-').map(Number);return monthKey(new Date(y,m-2,1));})():'';
 const previous=snapshots.find(s=>s.month===previousMonth);
 return <section className="page-section stock-controls"><div className="page-heading"><div><p className="eyebrow">Stock & purchasing</p><h1>Keep stock in balance.</h1></div></div>
 <p className="stock-notice">Records are saved in this browser. Team approval and shared records require the account backend; no purchases are sent to vendors here.</p>
 {error&&<p role="alert">{error}</p>}
 <details open><summary>Low-stock alerts <span>{low.length} items</span></summary>
 <div className="table-wrap"><table><thead><tr><th>Item / location</th><th>On hand / par</th><th>Suggested reorder</th><th>Estimated cost</th></tr></thead><tbody>{low.map(i=>{const needed=i.par-i.quantity;return <tr key={i.id}><td><button className="text-button" onClick={()=>onItem(i.id)}>{i.name}</button><small>{i.space}{i.status!=='Confirmed'?' · Verify count before ordering':''}</small></td><td>{i.quantity} / {i.par} {i.unit}</td><td><button className="text-button" onClick={()=>setSelected(String(i.id))}>{needed} {i.unit} · Compare vendors</button></td><td>{i.unitCost==null?'Cost needed':money(needed*i.unitCost)}</td></tr>})}</tbody></table>{!low.length&&<p>No items with a recorded par level are below par.</p>}</div></details>
 <details open><summary>Vendor comparison & purchase requests</summary>
 <label>Item<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose an item</option>{items.map(i=><option key={i.id} value={i.id}>{i.name} · {i.space}</option>)}</select></label>
 {chosen&&<><p>Compare the same product and specification. Prices are entered quotes, not live vendor prices.</p><form className="stock-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const q:Quote={id:crypto.randomUUID(),itemId:chosen.id,vendor:String(f.get('vendor')).trim(),pack:Number(f.get('pack')),price:Number(f.get('price')),shipping:Number(f.get('shipping')),minimum:Number(f.get('minimum')),days:Number(f.get('days'))};if(!q.vendor||![q.pack,q.price,q.shipping,q.minimum,q.days].every(Number.isFinite)||q.pack<=0||q.minimum<1||q.price<0||q.shipping<0||q.days<0)return;save({...data,quotes:[...data.quotes,q]});e.currentTarget.reset();}}>
 <label>Vendor<input name="vendor" required /></label><label>{chosen.unit} per pack<input name="pack" type="number" min="1" step="1" defaultValue="1" required /></label><label>Price per pack ($)<input name="price" type="number" min="0" step="0.01" required /></label><label>Shipping per order ($)<input name="shipping" type="number" min="0" step="0.01" defaultValue="0" required /></label><label>Minimum packs<input name="minimum" type="number" min="1" step="1" defaultValue="1" required /></label><label>Lead time (days)<input name="days" type="number" min="0" step="1" defaultValue="0" required /></label><button className="button" disabled={!ready}>Save vendor quote</button></form>
 <div className="table-wrap"><table><thead><tr><th>Vendor</th><th>Unit price</th><th>Order quantity</th><th>Total before tax</th><th>Lead time</th><th>Request</th></tr></thead><tbody>{quotes.map((q,index)=>{const o=orderCost(q,Math.max(1,chosen.par-chosen.quantity));return <tr key={q.id}><td>{q.vendor}{index===0&&quotes.length>1&&<small>Lowest order total</small>}</td><td>{money(q.price/q.pack)} / {chosen.unit}</td><td>{o.packs} packs · {o.units} {chosen.unit}</td><td>{money(o.total)}</td><td>{q.days} days</td><td><button className="button" disabled={!ready} onClick={()=>save({...data,purchases:[{id:crypto.randomUUID(),item:chosen.name+' · '+chosen.space,vendor:q.vendor,quantity:o.units,total:o.total,date:new Date().toISOString(),status:purchaseApproval(o.total)},...data.purchases]})}>Create draft</button> <button className="text-button" onClick={()=>save({...data,quotes:data.quotes.filter(v=>v.id!==q.id)})}>Remove quote</button></td></tr>})}</tbody></table></div></>}
 </details>
 <details><summary>Purchase approval policy & requests <span>{data.purchases.length}</span></summary><ul><li>$75 or less: no approval required.</li><li>Over $75 through $500: Eric must approve.</li><li>Over $500: Eric and Jess must both approve.</li></ul><p>Thresholds use the quoted total including shipping, before tax. Requests remain drafts until authenticated approval is connected.</p>{data.purchases.map(p=><article key={p.id}><strong>{p.item}</strong><p>{p.vendor} · {p.quantity} units · {money(p.total)} · {purchaseApproval(p.total)}</p><small>{new Date(p.date).toLocaleString()}</small></article>)}</details>
 <details><summary>Month-to-month inventory</summary><p>Save the current month’s dated count snapshot when your count is complete. Previous months are never invented or overwritten. Quantity change is net stock change, not consumption.</p><form className="stock-form" onSubmit={e=>{e.preventDefault();if(month!==monthKey(new Date())||data.snapshots.some(s=>s.month===month)){setError('Only the current month can be saved, once per month.');return;}save({...data,snapshots:[...data.snapshots,{month,date:new Date().toISOString(),items:items.map(i=>({...i}))}]});}}><label>Snapshot month<input type="month" min={monthKey(new Date())} max={monthKey(new Date())} value={month} onChange={e=>setMonth(e.target.value)} required /></label><button className="button" disabled={!ready||!items.length}>Save current counts</button></form>
 {latest&&<><p>{latest.month} snapshot saved {new Date(latest.date).toLocaleDateString()}. {previous?`Compared with ${previous.month}.`:`No ${previousMonth} snapshot; comparison is unavailable.`}</p><div className="table-wrap"><table><thead><tr><th>Item</th><th>Quantity</th><th>Quantity +/-</th><th>Unit cost</th><th>Unit cost +/-</th><th>Stock value</th><th>Value +/-</th></tr></thead><tbody>{latest.items.map(i=>{const before=previous?.items.find(p=>p.id===i.id);const delta=before?i.quantity-before.quantity:null;const value=i.unitCost==null?null:i.unitCost*i.quantity;const change=before&&before.unitCost!=null&&value!=null?value-before.unitCost*before.quantity:null;return <tr key={i.id}><td>{i.name}<small>{i.space}</small></td><td>{i.quantity} {i.unit}</td><td>{delta==null?'—':(delta>0?'+':'')+delta}</td><td>{i.unitCost==null?'Cost needed':money(i.unitCost)}</td><td>{before?.unitCost==null||i.unitCost==null?'—':(i.unitCost-before.unitCost>0?'+':'')+money(i.unitCost-before.unitCost)}</td><td>{value==null?'—':money(value)}</td><td>{change==null?'—':(change>0?'+':'')+money(change)}</td></tr>})}</tbody></table></div></>}
 </details></section>;
}
